---
- name: "Install and configure apache server"
  hosts: web_servers
  become: True
  roles:
    - roles/web

- name: "Install and configure mariadb database server"
  hosts: db_servers
  become: True
  roles:
    - roles/db